apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: longhorn-system
spec:
  redirectScheme:
    scheme: https
    permanent: true

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`k3s-storage-1`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: longhorn-frontend
      port: 80

---

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-redirect
  namespace: longhorn-system
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: longhorn-redirect-https@kubernetescrd
spec:
  rules:
  - host: k3s-storage-1
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80