- name: Check if Service Exists
  stat: path={{ systemd_dir }}/k3s.service
  register: service_status

- name: Stop Service
  service: name=k3s state=stopped
  when: service_status.stat.exists
  register: service_stopped

- name: Copy K3s service file
  register: k3s_service
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0644

- name: Copy K3 Config file
  template:
    src: "k3s.config.yml.j2"
    dest: "/etc/rancher/k3s/config.yml"
    owner: root
    group: root
    mode: 0644
  when: harden_enabled == false

- name: Copy K3S Harden Config file
  template:
    src: "k3s.config.harden.yml.j2"
    dest: "/etc/rancher/k3s/config.yml"
    owner: root
    group: root
    mode: 0644
  when: harden_enabled == true

- name: Create Audit-Log
  copy:
    content: ""
    dest: "/etc/rancher/k3s/audit-log"
    force: no
    group: root
    owner: root
    mode: 0644
  when: harden_enabled == true

- name: Remove Audit-Log file
  ansible.builtin.file:
    path: "/etc/rancher/k3s/audit-log"
    state: absent
  when: harden_enabled == false

- name: Copy Policy file
  template:
    src: "k3s.policy.yml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/policy.yml"
    owner: root
    group: root
    mode: 0644
  when: harden_enabled == true

- name: Remove Policy file
  ansible.builtin.file:
    path: "/var/lib/rancher/k3s/server/manifests/policy.yml"
    state: absent
  when: harden_enabled == false

- name: Enable and check K3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Wait for node-token
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token

- name: Register node-token file access mode
  stat:
    path: /var/lib/rancher/k3s/server
  register: p

- name: Change file access node-token
  file:
    path: /var/lib/rancher/k3s/server
    mode: "g+rx,o+rx"

- name: Read node-token from master
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: Store Master node-token
  set_fact:
    token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

- name: Restore node-token file access
  file:
    path: /var/lib/rancher/k3s/server
    mode: "{{ p.stat.mode }}"

- name: Create directory .kube
  file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: "u=rwx,g=rx,o="

- name: Change k3s.yaml permissions to 644
  file:
    path: /etc/rancher/k3s/k3s.yaml
    owner: "{{ ansible_user }}"
    mode: '644'

- name: Replace https://localhost:6443 by https://master-ip:6443
  command: >-
    k3s kubectl config set-cluster default
      --server=https://{{ master_ip }}:6443
      --kubeconfig ~{{ ansible_user }}/.kube/config
  changed_when: true

- name: Create kubectl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link

- name: copy config to local host
  fetch:
    src: /etc/rancher/k3s/k3s.yaml 
    dest: ~/.kube/{{ cluster_name }}-config
    flat: yes