# https://stackoverflow.com/questions/34333058/ansible-change-ssh-port-in-playbook

- name: "check port hardened ssh port"
  wait_for:
    port: "{{ ansible_port }}"
    state: "started"
    host: "{{ inventory_hostname }}"
    connect_timeout: "5"
    timeout: "5"
  delegate_to: "localhost"
  ignore_errors: true
  register: ssh_port

- name: "check port 22"
  wait_for:
    port: "22"
    state: "started"
    host: "{{ inventory_hostname }}"
    connect_timeout: "5"
    timeout: "5"
  delegate_to: "localhost"
  ignore_errors: true
  register: ssh_port_default
  when: 
    - ssh_port is defined 
    - ssh_port.state is undefined

- name: set SSH port to 22
  set_fact:
    ansible_port: "22"
  when: ssh_port_default.state is defined