# https://rancher.com/docs/k3s/latest/en/security/hardening_guide/

- name: Copy kernel file
  # register: k3s_service
  template:
    src: "90-kubelet.conf.j2"
    dest: "/etc/sysctl.d/90-kubelet.conf"
    owner: root
    group: root
    mode: 0644
  when: harden_enabled == true

- name: Load kernel conf
  ansible.builtin.command:
    argv:
      - sysctl
      - -p
      - /etc/sysctl.d/90-kubelet.conf
  become: yes
  when: harden_enabled == true

- name: Remove kernel file
  ansible.builtin.file:
    path: "/etc/sysctl.d/90-kubelet.conf"
    state: absent
  when: harden_enabled == false

- name: Reload kernel conf
  ansible.builtin.command:
    argv:
      - sysctl
      - -p
  become: yes
  when: harden_enabled == false