- name: test kubeconfig path
  stat:
    path: ~/.kube/{{ cluster_name }}-config
  register: kubeconfig_path

- name: replace host ip address in the kubeconfig
  replace:
    path: ~/.kube/{{ cluster_name }}-config
    regexp: 'https://127.0.0.1:6443'
    replace: "https://{{ master_ip }}:6443"
  when: kubeconfig_path

- name: change k3s.yaml permissions to 644
  file:
    path: ~/.kube/{{ cluster_name }}-config
    mode: '644'

- name: check if helm is installed /usr/local/bin/helm
  stat:
    path: $HOME/.config/helm/repositories.yaml
  register: helm_check

- name: download get-helm-3
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: ~/get-helm-3.sh
    mode: '700'
  when: not helm_check.stat.exists

- name: install helm if not exist
  command: >-
    ~/get-helm-3.sh
  when: not helm_check.stat.exists
  changed_when: true