---
- name: test kubeconfig path
  stat:
    path: ~/.kube/{{ cluster_name }}-config
  register: kubeconfig_path

- name: replace host ip address in the kubeconfig
  replace:
    path: ~/.kube/{{ cluster_name }}-config
    regexp: 'https://127.0.0.1:6443'
    replace: "https://{{ master_ip }}:6443"
  when: kubeconfig_path

- name: Change k3s.yaml permissions to 644
  file:
    path: ~/.kube/{{ cluster_name }}-config
    mode: '644'

# - name: Label Worker Nodes
#   command: >-
#     k3s kubectl label node k3s-worker-{{ item }} 'kubernetes.io/role=worker --overwrite'
#   with_sequence: start=1 end={{ groups['node'] | length }}
#   changed_when: true
#   ignore_errors: yes

# - name: Label Storage Nodes
#   command: >-
#     k3s kubectl label node k3s-storage-{{ item }} 'kubernetes.io/role=storage --overwrite'
#   with_sequence: start=1 end={{ groups['storage'] | length }}
#   changed_when: true
#   ignore_errors: yes

- name: check if helm is installed /usr/local/bin/helm
  stat:
    path: $HOME/.config/helm/repositories.yaml
  register: helm_check

- name: Download get-helm-3
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: ~/get-helm-3.sh
    mode: '700'
  when: not helm_check.stat.exists

- name: install helm if not exist
  command: >-
    ~/get-helm-3.sh
  when: not helm_check.stat.exists
  changed_when: true

# - name: Create a k3s namespace for the ingress
#   command: >-
#     kubectl create ns ingress-nginx
#   ignore_errors: yes

# - name: Deploy nginx-ingress to the cluster
#   command: >-
#     kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/baremetal/deploy.yaml