- name: copy k3s service file
  register: k3s_service
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755

- name: copy k3s config file
  template:
    src: "k3s.config.yml.j2"
    dest: "/etc/rancher/k3s/config.yml"
    owner: root
    group: root
    mode: 0644

- name: enable and check k3s service
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes