# https://artifacthub.io/packages/helm/longhorn/longhorn
- name: Add Longhorn Chart Repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: Deploy Longhorn Chart
  kubernetes.core.helm:
    name: longhorn
    wait: true
    namespace: longhorn-system
    create_namespace: true
    chart_ref: longhorn/longhorn
    values: "{{ lookup('template', 'longhorn-values.yml') | from_yaml }}"

- name: Deploy Ingress for Longhorn
  kubernetes.core.k8s:
    definition: '{{ item }}'
    namespace: longhorn-system
  with_items:
    - "{{ lookup('template', 'longhorn-network.yml', convert_data=False) }}"
  when:
    - item is not none